Fix "iw dev xxx link" command error
sysprog21/vwifi pull request #26
Opened 2022-06-10 11:44 UTC by qqgnoe466263

Fix command failed by using "iw dev xxx link".

This is a failed demonstration:

Connected to aa:b7:12:fd:11:77 (on owl0)
        SSID: TestAP
        freq: 2437
command failed: No such file or directory (-2)

2022-06-10 11:48 UTC, jserv commented on vwifi.c
> +    if (memcmp(mac, vif->bssid, ETH_ALEN) != 0)
Change the statement to
```c
if (!memcmp(mac, vif->bssid, ETH_ALEN))
```

2022-06-10 11:49 UTC, jserv commented on vwifi.c
> +    if (vif->sme_state == SME_CONNECTED) {
Add some comments to make it informative.

2022-06-10 13:50 UTC, rickywu0421 commented
I have figured out the error comes from, and I think you have misunderstand the actual meaning of `get_station()`.

1. Don't be misleading by the name `get_station()`: It is to get the information of the station based of the parameter `const u8 *mac`, and in this semantic, the station can be every interface including station and AP (Yes, including AP), rather than get all stations running in STA mode which are connected to BSS. Following is the sample usage:
```
iw dev <The interface performing search> station get <MAC address of someone who you are interesting in>
```

2. I found that `iw dev <interface> link` will find the AP which was informed to kernel via passing the AP's MAC into `cfg80211_connect_result()`, and then perform `get_station()` to show the AP's information. The question is, the AP's MAC address is not the same as the interface running in AP mode, rather, is a random MAC address. So kernel just passes the "fake" MAC address  as `const u8 *Mac` into `get_station()`, and not surprisingly, fails to find the interface owning the "fake" MAC address.

In conclusion, you should modify `start_ap()` by inserting real MAC address into `ap_info_entry_t` rather than keep using the fake MAC address.

2022-06-10 13:51 UTC, rickywu0421 requested changes
After discussing with @qqgnoe466263, I figured out I was misunderstood the meaning of `get_station()` too. @qqgnoe466263  will explain the correct semantic of `get_station()` latter.

2022-06-11 02:16 UTC, qqgnoe466263 commented
Yes, you are right, I misunderstood get_station. And this problem can be fixed when I use real MAC to start AP. Thank you for your detailed explanation!

2022-06-12 12:26 UTC, jserv commented
> Yes, you are right, I misunderstood get_station. And this problem can be fixed when I use real MAC to start AP. Thank you for your detailed explanation!

How about abandoning this pull request?

2022-06-12 12:30 UTC, qqgnoe466263 commented
I still discuss with @rickywu0421. And I'll check soon if this modification is not appropriate.

2022-06-12 13:44 UTC, rickywu0421 commented
> After thinking, i still feel that "get_station" can discuss and check. So I still discuss with @rickywu0421. And I'll check soon if this modification is not appropriate.

Yep, @qqgnoe466263 found that `get_station()` only do search when the parameter `const u8 mac` is the same as AP, I think it might be a security-based issue.

2022-06-13 06:28 UTC, rickywu0421 commented
> > Yes, you are right, I misunderstood get_station. And this problem can be fixed when I use real MAC to start AP. Thank you for your detailed explanation!
> 
> How about abandoning this pull request?

I think we could split this PR into two. One for changing `get_station()`, and another for fixing the error like title.

2022-06-13 13:45 UTC, jserv commented on vwifi.c
> +    /* For CFG80211_SIGNAL_TYPE_MBM, value is expressed in dbm */
Should be "dBm"
See https://en.wikipedia.org/wiki/DBm

2022-06-13 17:29 UTC, rickywu0421 commented on vwifi.c
> +    if (!memcmp(mac, vif->bssid, ETH_ALEN))
Should this line be opposite case? (`if (memcmp(mac, vif->bssid, ETH_ALEN))`)

2022-06-15 00:08 UTC, merged

2022-06-15 00:09 UTC, jserv commented
Thank @qqgnoe466263 for contributing!