Check kernel version for netif_tx_ni()
sysprog21/vwifi pull request #34
Opened 2023-02-17 08:07 UTC by quantabase13

According to this patch [1], kernel developers
prepared to replace netif_tx_ni() with netif_rx(). They modified netif_rx() and implement
netif_rx_ni() as a wrapper of netif_rx().

In the following patch [2], netif_tx_ni() was
removed. This patch was mentioned in networking
changes for 5.18.[3]

For the compatibility, I check kernel version
before calling netif_rx_ni().

[1]https://lore.kernel.org/netdev/20220202122848.647635-4-bigeasy@linutronix.de/ [2]https://lore.kernel.org/netdev/20220306215753.3156276-10-bigeasy@linutronix.de/ [3]https://lore.kernel.org/netdev/20220323180738.3978487-1-kuba@kernel.org/

2023-02-17 08:51 UTC, jserv requested changes
Avoid mentioning "According to this patch." Instead, you can specify the short hash of git commits.

2023-02-21 01:53 UTC, jserv requested changes
[Wrap the body at 72 characters](https://cbea.ms/git-commit/#wrap-72) according to [How to Write a Git Commit Message](https://cbea.ms/git-commit/).

2023-02-21 12:42 UTC, merged

2023-02-21 12:42 UTC, jserv commented
Thank @quantabase13 for contributing!

2023-02-21 12:48 UTC, quantabase13 commented
Thank for your quick response and patience too.