Implement cfg80211_ops->dump_station
sysprog21/vwifi pull request #36
Opened 2023-06-13 12:17 UTC by willwillhi1

The dump_station function is used to get statistics information for known stations. I also add validation tests to ensure proper implementation.

2023-06-13 12:19 UTC, jserv commented on vwifi.c
> +    if (sta_vif != ap_vif)
Rewrite as following:
```c
if (sta_vif == ap_vif)
    return ret;

ret = 0;
```

2023-06-14 02:24 UTC, willwillhi1 commented
Ok, I'm going to rewrite `owl_dump_station()` to use `owl_get_station()`

2023-06-15 03:10 UTC, jserv requested changes
Drop the commit "Correct behavior of owl_get_station()" within this pull request.

2023-06-15 03:20 UTC, willwillhi1 commented
Because owl_dump_station() will use owl_get_station(), so I think to correct owl_get_station() before implementing owl_dump_station().

2023-06-15 03:25 UTC, jserv commented
> Because owl_dump_station() will use owl_get_station(), so I think to correct owl_get_station() before implementing owl_dump_station().

Block this pull request until #37 is merged.

2023-06-16 06:02 UTC, jserv requested changes
Rebase the latest 'master' branch.

2023-06-28 09:23 UTC, rickywu0421 approved these changes

2023-06-28 11:15 UTC, merged

2023-06-28 11:15 UTC, jserv commented
Thank @willwillhi1 for contributing!