Corrected behavior of owl_get_station() and add owl_dump_station() function
sysprog21/vwifi pull request #37
Opened 2023-06-14 08:21 UTC by willwillhi1

2023-06-14 09:02 UTC, jserv requested changes
Emphasize on the fixes for owl_get_station() in this pull request.
For implementing dump_station(), please work on #36 .

2023-06-15 02:27 UTC, jserv requested changes
Read CONTRIBUTING.md carefully for consistent coding style.

2023-06-15 03:12 UTC, jserv commented on vwifi.c
> +    if (dev->ieee80211_ptr->iftype == NL80211_IFTYPE_AP) {
Rewrite `if` and `else if` with switch-case.

2023-06-15 05:58 UTC, rickywu0421 approved these changes

2023-06-16 06:01 UTC, merged

2023-06-16 06:01 UTC, jserv commented
Thank @willwillhi1 for contributing!