Add mac80211_hwsim configuration
sysprog21/vwifi pull request #5
Opened 2021-10-02 17:14 UTC by ldotrg

1. Add mac80211_hwsim demo configuration which include hostapd and wpa_supplicant.
    - Create a AP as a mock for "owl0 wifi"
    - In the future, "owl0" will replace the wpa_supplicant interface wlan0 
2. Fix verify.sh could not find common.sh file.

2021-10-02 17:33 UTC, jserv requested changes
Rebase the latest "main" branch

2021-10-02 17:35 UTC, jserv commented on scripts/mac80211_hwsim_demo.md
> +# mac80211_hwsim demo
Rename this file to `scripts/README.md`

2021-10-02 17:35 UTC, jserv commented on scripts/mac80211_hwsim_demo.md
> +```bash=
Annotate with `shell` rather than `bash=`.

2021-10-02 17:36 UTC, jserv commented on scripts/verify.sh
> +source $DEVENVROOT/scripts/common.sh
Send another pull request for this fix.

2021-10-02 17:37 UTC, jserv commented
By the way, can you address the motivation of this pull request? e.g., why does it make sense to `vwifi` development?

2021-10-03 02:09 UTC, jserv commented on scripts/wpa_supplicant.conf
> +# network={
Why did you leave unused item?

2021-10-03 05:49 UTC, ldotrg commented
Abort this pull request.
When mock AP is ready, I will create another pull request.

2021-10-03 05:49 UTC, closed without merging