Support transmit power
sysprog21/vwifi pull request #68
Opened 2024-06-02 09:47 UTC by jychen0611

Add `tx_power` to the virtual interface to describe the device's transmit power.

Implement `vwifi_set_tx_power` and `vwifi_get_tx_power` to correspond to `set_tx_power` and `get_tx_power` in cfg80211_ops, respectively.
`vwifi_set_tx_power` can set the device's transmit power, while `vwifi_get_tx_power` can retrieve the transmit power information.

The transmit power can be set using the **iwconfig vwn txpower** command.

![image](https://github.com/sysprog21/vwifi/assets/56495126/8f37a162-e9ed-45df-94da-d7a10aeb0248)

2024-06-02 13:08 UTC, jserv commented on vwifi.c
> +    /* 1 DBM = 100 MBM */
You should always use the notation "dBm," which stands for decibel-milliwatts.
See https://en.wikipedia.org/wiki/DBm

2024-06-02 13:12 UTC, jychen0611 commented
In the future, we may be able to introduce device coordinate parameters to calculate the RSSI value in free space in conjunction with transmit power.

2024-06-03 01:59 UTC, jserv requested changes
Improve the git commit message. Consider the following:
> This commit introduces 'tx_power' to the virtual interface to specify
the device's transmit power level. It also adds vwifi_set_tx_power()
and vwifi_get_tx_power() to align with 'set_tx_power' and 'get_tx_power'
in cfg80211_ops, respectively. The vwifi_set_tx_power() enables the
setting of the device's transmit power, whereas vwifi_get_tx_power()
facilitates the retrieval of this information.
> 
> Users can adjust the transmit power by employing the command:
>   iwconfig vwN txpower
>  where N stands for the entry of network interface.

Also, you should avoid using "iwconfig," which is deprecated. Use "iw" command for consistency.

See https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/#iwconfig

2024-06-03 17:24 UTC, jychen0611 commented
> Also, you should avoid using "iwconfig," which is deprecated. Use "iw" command for consistency.
> 
> See https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/#iwconfig

I'm currently facing an problem where using `sudo iw dev vw0 set txpower fixed 1000` results in 
```c
struct vwifi_vif *vif = wdev_get_vwifi_vif(wdev);
``` 
`wdev_get_vwifi_vif` returning an empty virtual interface.
That is, it fails the following check.
```c
/* Validate vif pointer */
if (!vif) {
    printk(KERN_ERR "vwifi_vif is NULL\n");
    return -EINVAL;
}
```

2024-06-04 13:01 UTC, jserv commented on vwifi.c
> +        pr_info("vwifi_vif is NULL\n");
Simply return without message since the error code does matter.

2024-06-04 13:02 UTC, jserv commented on vwifi.c
> +        pr_info("vwifi_vif is NULL\n");
Ditto.

2024-06-05 02:29 UTC, jserv commented
If this pull request is ready for reviewing, use `git rebase -i` to squash and refine the git commit message. Then, request the reviewers via GitHub web page.

2024-06-05 05:43 UTC, merged

2024-06-05 05:43 UTC, jserv commented
Thank @jychen0611 for contributing!